### ISSUE TITLE
Reconnect with E.ON Deutschland Owners

### ISSUE THREAD

**Issue by sabrinabuelig** [sabrinabuelig/Central-Europe#21]
Intro of Sabrina, understand the plan for 2018

**Comment by evamay-tado-solutions** [comment]
- [x] Jan-Philipp Rombolotto
- [x] Michael Visnjic, Peter Walter, Rebecca Poppele, rebecca.poppele@eon.com, rebecca.poppele@eon.com, Project Manager Digital Marketing
- [x] Stefan Moriße, Pressesprecher/Referent Unternehmenskommunikation, Rainer Stechl, rainer.stechl@eon.com, Markenkommunikation / Marketing, Werner Ressl, Markenführung, Werbung und Sponsoring
- [x] bjoern.deuster@eon.com User Experience Manager,  friederike.kellersmann@eon.com, Manager Strategisches Marketing, fabian.riether@eon.com, Senior Product Designer, timon.oberheide@eon.com
- [x] Viktor Völker, Team Lead Product, viktor.voelker@eon.com
- [x] Inga Spreitzer, inga.spreitzer@eon.com
- [ ] mare.civadelic@eon.com
